include "algorithm.asyhdr";
include "../data/Comet.dat";

setView(45, 35.2, 0);

figureBegin();
Comet();
highline(BB--FAB--HBD--FFB);
highline(DAF--CAB--GAB--IABD);
highline(DFA--CFB--GFB--IFBD);
highline(GAB--IABD--HBD--FAB);
highline(GFB--IFBD--HBD--FFB);
highline(BB--FAB--HBA--FBB);
highline(DAB--CAB--GAB--IABA);
highline(DBA--CBB--GBB--IBBA);
highline(GAB--IABA--HBA--FAB);
highline(GBB--IBBA--HBA--FBB);
highline(BB--FBB--HBF--FFB);
highline(DBF--CBB--GBB--IBBF);
highline(DFB--CFB--GFB--IFBF);
highline(GBB--IBBF--HBF--FBB);
highline(GFB--IFBF--HBF--FFB);
highline(CAB--DAB--EA--DAF);
highline(CFB--DFA--EF--DFB);
highline(CBB--DBA--EB--DBF);
makeChange(BB--FAB--HBA--FBB, DAB--CAB--GAB--IABA, findCenter(GAB--IABA--HBA--FAB)+0.05*(-Y-Z));
makeChange(DAF--CAB--GAB--IABD, BB--FAB--HBD--FFB, findCenter(GAB--IABD--HBD--FAB)+0.05*(X-Z));
makeChange(DBA--CBB--GBB--IBBA, DFA--CFB--GFB--IFBD, 0.55*(BB+FAB));
makeChange(DFB--CFB--GFB--IFBF, DBA--CBB--GBB--IBBA, 1.0*GBB+0.1*(X-Y));
makeChange(GBB--IBBA--HBA--FBB, GAB--IABA--HBA--FAB, 1.15*HBA);
makeChange(GAB--IABD--HBD--FAB, GFB--IFBD--HBD--FFB, 1.15*HBD);
makeChange(GFB--IFBD--HBD--FFB, GBB--IBBF--HBF--FBB, 1.0*FFB+0.1*(X-Y));
figureLine();
Comet();
makeMove(7*(-Y-Z)/15, 70.5, 0.65);
label("$L^{0.39}$", 1.15*BF);
figureNext();
Comet();
makeMove(7*(X-Z)/15, -70.5, 0.65);
label("$R^{-0.39}$", 1.15*BF);
figureNext();
Comet();
makeMove(7*(-Y-Z)/15, -70.5, 0.65);
label("$L^{-0.39}$", 1.15*BF);
figureNext();
Comet();
makeMove(7*(X-Z)/15, 70.5, 0.65);
label("$R^{0.39}$", 1.15*BF);
figureEnd();
