include "algorithm.asyhdr";
include "../data/Cube3.dat";

setView(135, -35.2, 0);

figureBegin();
Cube3();
highline(AA--BAB--CABC--BAC);
highline(AB--BBA--CBAD--BBD);
highline(AD--BDB--CDBC--BDC);
highline(AA--BAB--CABE--BAE);
highline(AB--BBA--CBAF--BBF);
highline(AA--BAC--CACE--BAE);
makeChange(AA--BAB--CABC--BAC, AB--BBA--CBAD--BBD, 1.1*X+2*Y/3);
makeChange(AB--BBA--CBAF--BBF, AD--BDB--CDBC--BDC, 1.1*X+Y-2*Z/3);
makeChange(AD--BDB--CDBC--BDC, AA--BAC--CACE--BAE, X+0.3*Y+1.1*Z);
figureLine();
Cube3();
makeMove(0.6*X, 90, 1.5);
makeMove(0.7*X, -90, 1.5);
makeMove(0.6*Y, -90, 1.5);
makeMove(0.7*Y, 90, 1.5);
label("$F$ ($F^{-1}$)", 1.7*Z);
figureNext();
Cube3();
makeMove(-2*Z/3, 90, 1.5);
label("$D$ ($D^2$, $D^3$)", 1.7*Z);
figureNext();
Cube3();
makeMove(0.6*X, -90, 1.5);
makeMove(0.7*X, 90, 1.5);
makeMove(0.6*Y, 90, 1.5);
makeMove(0.7*Y, -90, 1.5);
label("$F^{-1}$ ($F$)", 1.7*Z);
figureNext();
Cube3();
makeMove(-2*Z/3, -90, 1.5);
label("$D^{-1}$ ($D^{-2}$, $D^{-3}$)", 1.7*Z);
figureEnd();
