include "algorithm.asyhdr";
include "../data/DodecahedronSkewb.dat";

setView(0, -90, 0);

figureBegin();
DodecahedronSkewb();
highline(AM--BEM--CE--BIM);
highline(AQ--BEQ--CE--BJQ);
highline(AI--BIM--CE--BJQ--AJ);
highline(AJ--BJQ--CJ--BJS);
highline(AQ--BJQ--CJ--BCQ);
highline(AS--BJS--CJ--BDS);
highline(AC--BCQ--CJ--BDS--AD);
highline(AI--BIM--CI--BIO);
highline(AM--BIM--CI--BAM);
highline(AO--BIO--CI--BBO);
highline(AA--BAM--CI--BBO--AB);
highline(AG--BGO--CG--BGS);
highline(AO--BGO--CG--BIO);
highline(AS--BGS--CG--BJS);
highline(AI--BIO--CG--BJS--AJ);
makeChange(AJ--BJQ--CJ--BJS, AG--BGO--CG--BGS, 0.55*(BJS+AJ));
makeChange(AG--BGO--CG--BGS, AI--BIM--CI--BIO, 0.55*(BIO+AI));
makeChange(AC--BCR--CL--BDT--AD, AA--BAM--CI--BBO--AB, 1.3*AJ+0.1*AE);
makeChange(AA--BAM--CI--BBO--AB, AC--BCQ--CJ--BDS--AD, 0.65*(AI+AJ)+0.1*AG);
makeChange(AQ--BJQ--CJ--BCQ, AQ--BEQ--CE--BJQ, 0.55*(BJQ+AQ));
makeChange(AM--BEM--CE--BIM, AM--BIM--CI--BAM, 0.55*(BIM+AM));
makeChange(AS--BJS--CJ--BDS, AS--BGS--CG--BJS, 0.55*(BJS+AS));
makeChange(AO--BGO--CG--BIO, AO--BIO--CI--BBO, 0.55*(BIO+AO));
figureLine();
DodecahedronSkewb();
makeMove(AS/3, 120, 1.0);
label("$L$", 1.15*AE);
figureNext();
DodecahedronSkewb();
makeMove(AO/3, -120, 1.0);
label("$R^{-1}$", 1.15*AE);
figureNext();
DodecahedronSkewb();
makeMove(AS/3, -120, 1.0);
label("$L^{-1}$", 1.15*AE);
figureNext();
DodecahedronSkewb();
makeMove(AO/3, 120, 1.0);
label("$R$", 1.15*AE);
figureEnd();
