include "algorithm.asyhdr";
include "../data/Gem34.dat";

setView(0, -20, 0);

figureBegin();
Gem3();
highline(BA--BG--BE--BH);
highline(BA--BH--BD--BI);
highline(CA--CH--CD--CI);
highline(HA--BH--BE--PF);
highline(HB--BH--BD--PE);
highline(HC--CI--CD--PA);
highline(LA--BG--BE--PF);
highline(GC--CH--CD--PA);
makeChange(HC--CI--CD--PA, HA--BH--BE--PF, 1.1*HD+0.1*HE);
makeChange(BA--BG--BE--BH, BA--BH--BD--BI, 0.55*(BA+BH));
makeChange(HB--BH--BD--PE, GC--CH--CD--PA, PA);
figureLine();
Gem3();
makeMove(5*(-X-Y+Z)/12, -120, 0.8);
label("$L^{-1}$", 1.2*Z);
figureNext();
Gem3();
makeMove(5*(X-Y+Z)/12, 120, 0.8);
label("$R$", 1.2*Z);
figureNext();
Gem3();
makeMove(5*(-X-Y+Z)/12, 120, 0.8);
label("$L$", 1.2*Z);
figureNext();
Gem3();
makeMove(5*(X-Y+Z)/12, -120, 0.8);
label("$R^{-1}$", 1.2*Z);
figureNext();
Gem3();
makeMove(7*Z/8, -90, 0.7);
label("$U^{-1}$", 1.2*Z);
figureLine();
Gem3();
makeMove(5*(X-Y+Z)/12, 120, 0.8);
label("$R$", 1.2*Z);
figureNext();
Gem3();
makeMove(5*(-X-Y+Z)/12, -120, 0.8);
label("$L^{-1}$", 1.2*Z);
figureNext();
Gem3();
makeMove(5*(X-Y+Z)/12, -120, 0.8);
label("$R^{-1}$", 1.2*Z);
figureNext();
Gem3();
makeMove(5*(-X-Y+Z)/12, 120, 0.8);
label("$L$", 1.2*Z);
figureNext();
Gem3();
makeMove(7*Z/8, 90, 0.7);
label("$U$", 1.2*Z);
figureEnd();
