include "algorithm.asyhdr";
include "../data/Gem5.dat";

setView(45, -35.2, 0);

figureBegin();
Gem5();
label("$\times 2$", 1.25*EF);
highline(DC--DB--DE--DF);
highline(AA--AB--AF--AE);
highline(AC--AD--AE--AF);
highline(HA--HB--HC);
highline(GA--GB--GC);
highline(JA--JB--JC);
highline(AB--GB--GC--AA);
highline(AD--HB--HC--AC);
highline(DC--DB--JA--JC);
makeChange(DC--DB--DE--DF, AA--AB--AF--AE, 0.45*(AF+DE+EE));
makeChange(AA--AB--AF--AE, AC--AD--AE--AF, 0.55*(AE+AF));
makeChange(AC--AD--AE--AF, DC--DB--DE--DF, 1.1*DE);
makeChange(GA--GB--GC, HA--HB--HC, 0.67*(AE+AF));
makeChange(JA--JB--JC, GA--GB--GC, 0.67*(EE+EF));
makeChange(HA--HB--HC, JA--JB--JC, 0.67*(DE+DF));
figureLine();
Gem5();
makeMove((X-Y-Z)/2, -120, 0.9);
label("$D^{-1}$", 1.15*EF);
figureNext();
Gem5();
makeMove((X-Y+Z)/3, 120, 1);
label("$C$", 1.15*EF);
figureNext();
Gem5();
makeMove((X-Y-Z)/2, 120, 0.9);
label("$D$", 1.15*EF);
figureNext();
Gem5();
makeMove((X-Y+Z)/3, 120, 1);
label("$C$", 1.15*EF);
figureEnd();
