include "algorithm.asyhdr";
include "../data/Gem7.dat";

setView(0, -45, 0);

figureBegin();
Gem7();
highline(GA--GC--UD--GD);
highline(CA--CC--UA--CD);
highline(CC--UB--MC--MF);
highline(GC--UC--MC--MI);
highline(CD--UF--KE--KG);
highline(MA--MC--MI--MD);
highline(MA--MB--MF--MC);
highline(KA--KC--KI--KD);
highline(KA--KE--KG--KB);
highline(CA--CB--PD--CD);
highline(CD--PE--KB--KG);
highline(CA--CB--RA--CC);
highline(CC--RF--MB--MF);
highline(GA--GB--ZD--GD);
highline(ED--ZF--KD--KI);
highline(GA--GB--YA--GC);
highline(GC--YF--MD--MI);
makeChange(GA--GC--UD--GD, CA--CC--UA--CD, 1.1*Z-Y);
makeChange(MA--MC--MI--MD, MA--MB--MF--MC, 0.55*(MA+MC));
makeChange(KA--KC--KI--KD, KA--KE--KG--KB, 1.1*KA);
figureLine();
Gem7();
makeMove(7*(Z-Y)/12, 180, 0.75);
label("$C$", 1.15*KC);
figureNext();
Gem7();
makeMove(11*Z/12, -90, 0.65);
label("$U^{-1}$", 1.15*KC);
figureNext();
Gem7();
makeMove(7*(Z-Y)/12, 180, 0.75);
label("$C$", 1.15*KC);
figureNext();
Gem7();
makeMove(11*Z/12, 90, 0.65);
label("$U$", 1.15*KC);
figureNext();
Gem7();
makeMove(7*(Z-Y)/12, 180, 0.75);
label("$C$", 1.15*KC);
figureLine();
Gem7();
makeMove(11*Z/12, -90, 0.65);
label("$U^{-1}$", 1.15*KC);
figureNext();
Gem7();
makeMove(7*(Z-Y)/12, 180, 0.75);
label("$C$", 1.15*KC);
figureNext();
Gem7();
makeMove(11*Z/12, 90, 0.65);
label("$U$", 1.15*KC);
figureNext();
Gem7();
makeMove(7*(Z-Y)/12, 180, 0.75);
label("$C$", 1.15*KC);
figureEnd();
