include "algorithm.asyhdr";
include "../data/Hexadecagon.dat";

setView(45, -35.2, 0);

figureBegin();
Hexadecagon();
highline(EG--EGB--HA--EGD);
highline(EGD--HA--HB--DDG);
highline(DD--DDG--HB--DDE);
highline(BAG--HE--HA--EGB);
highline(BA--BAF--HE--BAG);
highline(AF--AFE--AFH--AFA);
highline(EG--EGA--LA--EGD);
highline(EGA--LA--LB--AFG);
highline(AF--AFG--LB--AFE);
highline(DDG--LE--LA--EGD);
highline(DD--DDC--LE--DDG);
highline(BA--BAF--BAH--BAB);
highline(EG--EGA--QA--EGB);
highline(EGB--QA--QB--BAG);
highline(BA--BAG--QB--BAB);
highline(AFG--QE--QA--EGA);
highline(AF--AFA--QE--AFG);
highline(DD--DDC--DDH--DDE);
makeChange(EG--EGB--HA--EGD, BA--BAF--HE--BAG, 1.1*findCenter(BAG--HE--HA--EGB));
makeChange(BA--BAG--QB--BAB, EG--EGA--QA--EGB, 1.1*findCenter(EGB--QA--QB--BAG));
makeChange(DD--DDG--HB--DDE, AF--AFA--QE--AFG, 0.55*(EG+EGB));
makeChange(AF--AFG--LB--AFE, DD--DDG--HB--DDE, 1.1*DDG+0.1*FI);
makeChange(EGD--HA--HB--DDG, BAG--HE--HA--EGB, 1.05*HA);
makeChange(EGB--QA--QB--BAG, AFG--QE--QA--EGA, 1.05*QA);
makeChange(AFG--QE--QA--EGA, DDG--LE--LA--EGD, 1.05*EGA);
figureLine();
Hexadecagon();
makeMove(0.9*FH, 72, 0.62);
label("$L$", 1.15*FF);
figureNext();
Hexadecagon();
makeMove(0.9*FG, -72, 0.62);
label("$R^{-1}$", 1.15*FF);
figureNext();
Hexadecagon();
makeMove(0.9*FH, -72, 0.62);
label("$L^{-1}$", 1.15*FF);
figureNext();
Hexadecagon();
makeMove(0.9*FG, 72, 0.62);
label("$R$", 1.15*FF);
figureEnd();
