include "algorithm.asyhdr";
include "../data/MasterSkewb.dat";

setView(135, -35.2, 0);

figureBegin();
MasterSkewb();
highline(BAB--CA--CB--BAC);
highline(BDB--CC--CD--BDC);
highline(CA--CB--CD--CC);
highline(AA--BAB--BAC);
highline(AD--BDB--BDC);
highline(BAC--EA--EB--BAE);
highline(BGC--EC--ED--BGE);
highline(EA--EB--ED--EC);
highline(AA--BAC--BAE);
highline(AG--BGC--BGE);
highline(BAB--DA--DB--BAE);
highline(BFB--DC--DD--BFE);
highline(DA--DB--DD--DC);
highline(AA--BAB--BAE);
highline(AF--BFB--BFE);
makeChange(BDB--CC--CD--BDC, BAC--EA--EB--BAE, 1.1*BAC);
makeChange(BAB--CA--CB--BAC, BGC--EC--ED--BGE, 1.1*BAC);
makeChange(CA--CB--CD--CC, EA--EB--ED--EC, 0.55*(AA+AC));
makeChange(AA--BAB--BAC, AG--BGC--BGE, 1.1*BAC);
makeChange(BGC--EC--ED--BGE, BAB--DA--DB--BAE, 1.1*BAE);
makeChange(BAC--EA--EB--BAE, BFB--DC--DD--BFE, 1.1*BAE);
makeChange(EA--EB--ED--EC, DA--DB--DD--DC, 0.55*(AA+AE));
makeChange(AG--BGC--BGE, AA--BAB--BAE, 1.1*BAE);
makeChange(BAB--DA--DB--BAE, BAB--CA--CB--BAC, 1.1*BAB);
makeChange(BFB--DC--DD--BFE, BDB--CC--CD--BDC, 1.1*BBA);
makeChange(DA--DB--DD--DC, CA--CB--CD--CC, 0.55*(AA+AB));
makeChange(AF--BFB--BFE, AD--BDB--BDC, 0.55(AB+BBA));
figureLine();
MasterSkewb();
makeMove(AC/2, -120, 1.25);
label("$L^{-1}$", 1.7*Z);
figureNext();
MasterSkewb();
makeMove(AE/2, 120, 1.25);
label("$R$", 1.7*Z);
figureNext();
MasterSkewb();
makeMove(AC/2, 120, 1.25);
label("$L$", 1.7*Z);
figureNext();
MasterSkewb();
makeMove(AE/2, -120, 1.25);
label("$R^{-1}$", 1.7*Z);
figureEnd();
