include "algorithm.asyhdr";
include "../data/Octahedron4.dat";

setView(0, 0, 0);

figureBegin();
Octahedron4();
highline(BDE--BD2E--CDBE);
highline(BDE--BD2E--CDAE);
highline(BAD--BA2D--CADE);
highline(BAD--BA2D--CADF);
highline(BFB--BB2F--CFBD);
makeChange(BAD--BA2D--CADF, BDE--BD2E--CDBE, 1.2*BDA);
makeChange(BFB--BB2F--CFBD, BAD--BA2D--CADE, 1.4*BD2F);
makeChange(BDE--BD2E--CDAE, BFB--BB2F--CFBD, 1.2*BDB);
figureLine();
Octahedron4();
makeMove((X+Y-Z)/12, 120, 0.8);
makeMove((X+Y-Z)/4, 120, 0.8);
label("$Dd$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((-X-Y+Z)/4, -120, 0.8);
label("$L^{-1}$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((X-Y+Z)/4, 120, 0.8);
label("$R$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((-X-Y+Z)/4, 120, 0.8);
label("$L$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((X-Y+Z)/4, -120, 0.8);
label("$R^{-1}$", 1.2*AE);
figureLine();
Octahedron4();
makeMove((X+Y-Z)/12, -120, 0.8);
makeMove((X+Y-Z)/4, -120, 0.8);
label("$D^{-1}d^{-1}$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((X-Y+Z)/4, 120, 0.8);
label("$R$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((-X-Y+Z)/4, -120, 0.8);
label("$L^{-1}$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((X-Y+Z)/4, -120, 0.8);
label("$R^{-1}$", 1.2*AE);
figureNext();
Octahedron4();
makeMove((-X-Y+Z)/4, 120, 0.8);
label("$L$", 1.2*AE);
figureEnd();

