include "algorithm.asyhdr";
include "../data/Octahedron3.dat";

setView(-45, -35.2, -60);

figureBegin();
Octahedron3();
label("$\times 2$", 1.5*CBCE);
highline(BBD--BDB--CBDF);
highline(BBE--BEB--CBCE);
highline(BDE--BED--CADE);
highline(BBD--BDB--CBDE);
highline(BBE--BEB--CBDE);
highline(BDE--BED--CBDE);
highline(BBD--BBE--CBDE);
highline(BDB--BDE--CBDE);
highline(BEB--BED--CBDE);
makeChange(BBD--BDB--CBDE, BBE--BEB--CBDE, 0.2*(AB+5*CBDE));
makeChange(BBE--BEB--CBDE, BDE--BED--CBDE, 0.2*(AE+5*CBDE));
makeChange(BDE--BED--CBDE, BBD--BDB--CBDE, 0.2*(AD+5*CBDE));
makeChange(BDB--BDE--CBDE, BBD--BBE--CBDE, 0.2*(BBD+BDB+4*CBDE));
makeChange(BEB--BED--CBDE, BDB--BDE--CBDE, 0.2*(BDE+BED+4*CBDE));
makeChange(BBD--BBE--CBDE, BEB--BED--CBDE, 0.2*(BBE+BEB+4*CBDE));
figureLine();
Octahedron3();
makeMove(2*CADF/3, -120, 0.8);
label("$D^{-1}$", 1.5*CBCE);
figureNext();
Octahedron3();
makeMove(2*CBDE/3, 120, 0.8);
label("$C$", 1.5*CBCE);
figureNext();
Octahedron3();
makeMove(2*CADF/3, 120, 0.8);
label("$D$", 1.5*CBCE);
figureNext();
Octahedron3();
makeMove(2*CBDE/3, 120, 0.8);
label("$C$", 1.5*CBCE);
figureEnd();
