include "algorithm.asyhdr";
include "../data/Rainbow.dat";

figureBegin();
Rainbow();
highline(EA--ED--C--EE);
highline(C--DD--ED);
highline(C--DE--EE);
highline(EA--EE--L--EB);
highline(L--CC--EB);
highline(L--CD--EE);
highline(EA--EB--B--EC);
highline(B--AD--EC);
highline(B--AE--EB);
makeChange(C--DD--ED, L--CC--EB, -1.7*Y+(-X+Z)/4);
makeChange(L--CD--EE, B--AD--EC, -1.7*Y+(X+Z)/4);
makeChange(EA--EB--B--EC, EA--ED--C--EE, -1.3*Y-Z/10);
figureLine();
Rainbow();
makeMove((-X-Y+Z)/2, -120, 1.0);
label("$L^{-1}$", 1.5*Z);
figureNext();
Rainbow();
makeMove((X-Y+Z)/2, 120, 1.0);
label("$R$", 1.5*Z);
figureNext();
Rainbow();
makeMove((-X-Y+Z)/2, 120, 1.0);
label("$L$", 1.5*Z);
figureNext();
Rainbow();
makeMove((X-Y+Z)/2, -120, 1.0);
label("$R^{-1}$", 1.5*Z);
figureEnd();
