include "algorithm.asyhdr";
include "../data/Rhombododecahedron3.dat";

setView(45, 0, 0);

figureBegin();
Rhombododecahedron3();
highline(DFD--CDF--EDB--GDBFE);
highline(DFD--CDF--EDF--GDFFH);
highline(DFF--CFF--EFD--GFDFH);
highline(DFF--CFF--EFB--GFBFB);
highline(DBB--CBB--EBF--GBFBF);
highline(DBB--CBB--EBA--GBABA);
highline(DBA--CAB--EAB--GABBA);
highline(DBA--CAB--EAF--GAFBD);
highline(DFD--FFE--GDBFE);
highline(DFD--FFH--GDFFH);
highline(DFF--FFH--GFDFH);
highline(DBB--FBF--GBFBF);
highline(DFF--FFB--GFBFB);
highline(DBB--FBA--GBABA);
highline(DBA--FBA--GABBA);
highline(DBA--FBD--GAFBD);
makeChange(DFF--CFF--EFD--GFDFH, DBB--CBB--EBA--GBABA, 0.8*(X-Y)+0.1*X);
makeChange(DFD--CDF--EDB--GDBFE, DBA--CAB--EAF--GAFBD, 0.8*(X-Y)+0.1*X);
makeChange(DFD--FFE--GDBFE, DBA--FBD--GAFBD, 0.8*(X-Y)+0.1*X);
makeChange(DFF--FFH--GFDFH, DBB--FBA--GBABA, 0.8*(X-Y)+0.1*X);
figureLine();
Rhombododecahedron3();
makeMove(5*(Z-Y)/12, 70.5, 0.72);
label("$U^{0.39}$", 1.1*Z);
figureNext();
Rhombododecahedron3();
makeMove(5*(-Z+X)/12, 70.5, 0.72);
label("$D^{0.39}$", 1.1*Z);
figureNext();
Rhombododecahedron3();
makeMove(5*(X-Y)/12, 180, 0.75);
label("$C$", 1.1*Z);
figureNext();
Rhombododecahedron3();
makeMove(5*(-Z+X)/12, -70.5, 0.72);
label("$D^{-0.39}$", 1.1*Z);
figureNext();
Rhombododecahedron3();
makeMove(5*(Z-Y)/12, -70.5, 0.72);
label("$U^{-0.39}$", 1.1*Z);
figureEnd();
