include "algorithm.asyhdr";
include "../data/Rhombododecahedron2.dat";

void makeTurnRight(real angle, real radius = 1.2, triple axes = forward)
{
	real halfAngle = angle / 2;
	axes = unit(axes);
	triple fixedX = rotate(90, forward) * fixedZ;
	triple left = axes * dot(fixedX, axes) - radius * unit(fixedX);
	triple start = rotate(halfAngle, axes) * left;
	triple stop = rotate(-halfAngle, axes) * left;
	draw(start..left..stop, Arrow3);
}

setView(0, -45, 0);

figureBegin();
Rhombododecahedron2();
highline(BA--BE--BB);
highline(BA--BD--BE);
highline(BA--BB--BC);
highline(CA--CE--CB);
highline(CA--CD--CE);
makeChange(BA--BE--BB, BA--BB--BC, 0.53*(BA+BB));
makeChange(BA--BD--BE, BA--BE--BB, 0.53*(BA+BE));
makeChange(BA--BC--BD, BA--BD--BE, 0.53*(BA+BD));
makeChange(BA--BB--BC, BA--BC--BD, 0.53*(BA+BC));
makeChange(CA--CD--CE, CA--CE--CB, 0.53*(CA+CE));
makeChange(CA--CE--CB, CA--CB--CC, 0.53*(CA+CB));
makeChange(CA--CB--CC, CA--CC--CD, 0.53*(CA+CC));
makeChange(CA--CC--CD, CA--CD--CE, 0.53*(CA+CD));
figureLine();
Rhombododecahedron2();
makeMove(3*(Z+X)/8, -180, 0.75);
makeMove(3*(Z-X)/8, -180, 0.75);
label("$F_1$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeMove(3*(-Y+X)/8, -180, 0.75);
makeMove(3*(-Y-X)/8, -180, 0.75);
label("$F_2$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeMove(3*(Z+X)/8, -180, 0.75);
makeMove(3*(Z-X)/8, -180, 0.75);
label("$F_1$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeMove(3*(-Y+X)/8, -180, 0.75);
makeMove(3*(-Y-X)/8, -180, 0.75);
label("$F_2$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeTurnRight(-120, 1.1, HE);
label("$T^{-1}$", 0.73*(Z+Y));
figureLine();
Rhombododecahedron2();
makeMove(3*(-Y+X)/8, 180, 0.75);
makeMove(3*(-Y-X)/8, 180, 0.75);
label("$F_2^{-1}$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeMove(3*(Z+X)/8, 180, 0.75);
makeMove(3*(Z-X)/8, 180, 0.75);
label("$F_1^{-1}$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeMove(3*(-Y+X)/8, 180, 0.75);
makeMove(3*(-Y-X)/8, 180, 0.75);
label("$F_2^{-1}$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeMove(3*(Z+X)/8, 180, 0.75);
makeMove(3*(Z-X)/8, 180, 0.75);
label("$F_1^{-1}$", 0.73*(Z+Y));
figureNext();
Rhombododecahedron2();
makeTurnRight(120, 1.1, HE);
label("$T$", 0.73*(Z+Y));
figureEnd();
