include "algorithm.asyhdr";
include "../data/Starminx.dat";

setView(-44.2, 35.2, -98.25);

init();
triple fw = findCenter(AG--AS--AD--AT--AH);
triple bw = findCenter(AK--AN--AF--AR--AL);
triple lt = findCenter(AK--AP--AH--AT--AL);
triple rt = findCenter(AC--AQ--AJ--AS--AD);
triple up = findCenter(AC--AR--AL--AT--AD);
triple bl = findCenter(AG--AO--AB--AP--AH);

figureBegin();
Starminx();
highline(BA--BB--BC--BD--BE);
highline(AL--BB--BC);
highline(AD--BD--BE);
highline(GA--GB--GC--GD--GE);
highline(AT--GC--GD);
highline(AG--GE--GA);
highline(FA--FB--FC--FD--FE);
highline(AK--FE--FA);
highline(AH--FB--FC);
makeChange(BA--BB--BC--BD--BE, GA--GB--GC--GD--GE, 0.7*(fw+up+0.1*rt));
makeChange(GA--GB--GC--GD--GE, FA--FB--FC--FD--FE, 0.7*(fw+lt+0.1*bl));
makeChange(FA--FB--FC--FD--FE, BA--BB--BC--BD--BE, 0.7*(lt+up+0.1*fw));
makeChange(AL--BB--BC, AT--GC--GD, 0.64*(fw+up+0.5*lt));
makeChange(AT--GC--GD, AK--FE--FA, 0.64*(fw+lt+0.5*up));
makeChange(AK--FE--FA, AL--BB--BC, 0.64*(lt+up+0.5*bw));
makeChange(AD--BD--BE, AG--GE--GA, 0.64*(fw+up+0.5*rt));
makeChange(AG--GE--GA, AH--FB--FC, 0.64*(fw+lt+0.5*bl));
makeChange(AH--FB--FC, AD--BD--BE, 0.64*(lt+up+0.5*fw));
figureLine();
Starminx();
makeMove(0.75*lt, 72, 0.79);
makeMove(0.65*lt, -72, 0.81);
makeMove(0.65*rt, -72, 0.81);
makeMove(0.75*rt, 72, 0.79);
label("$F$", 0.57*(AC+AR));
figureNext();
Starminx();
makeMove(0.7*bl, 72, 0.8);
label("$D$", 0.57*(AC+AR));
figureNext();
Starminx();
makeMove(0.75*lt, -72, 0.79);
makeMove(0.65*lt, 72, 0.81);
makeMove(0.65*rt, 72, 0.81);
makeMove(0.75*rt, -72, 0.79);
label("$F^{-1}$", 0.57*(AC+AR));
figureNext();
Starminx();
makeMove(0.7*bl, -72, 0.8);
label("$D^{-1}$", 0.57*(AC+AR));
figureEnd();
