include "algorithm.asyhdr";
include "../data/SunCube.dat";

setView(45, -35.2, 0);

figureBegin();
SunCube();
label("$\times 7$", 1.7*Z);
highline(BCA--CCAG--GA--DACEG);
highline(BCG--CCAG--GH--DCGAE);
highline(CCAG--GH--GA);
highline(BAC--CACE--GB--DACEG);
highline(DACEG--GA--GB);
makeChange(CCAG--GH--GA, DACEG--GA--GB, 1.15*GA);
makeChange(DACEG--GA--GB, DBDFH--HA--HB, 0.52*(BCA+BAC));
makeChange(DBDFH--HA--HB, CCAG--GH--GA, 1.1*BCA);
makeChange(BDB--CDBH--HA--DBDFH, BCA--CCAG--GA--DACEG, 1.04*BCA);
makeChange(BBD--CBDF--HB--DBDFH, BCG--CCAG--GH--DCGAE, 0.59*(BDB+BBD));
makeChange(BAC--CACE--GB--DACEG, BBD--CBDF--HB--DBDFH, 1.0*BAC);
makeChange(BCG--CCAG--GH--DCGAE, BAC--CACE--GB--DACEG, 0.7*(CCAG+DACEG));
figureNext();
setViewAbsolute(45, 35.2, 0);
SunCube();
label(" ", 3.2*Z);
highline(BDB--CDBH--HA--DBDFH);
highline(BBD--CBDF--HB--DBDFH);
highline(DBDFH--HA--HB);
makeChange(DACEG--GA--GB, DBDFH--HA--HB, 0.52*(BDB+BBD));
makeChange(DBDFH--HA--HB, CCAG--GH--GA, 0.54*BDB+0.5*BBD);
makeChange(BCA--CCAG--GA--DACEG, BDB--CDBH--HA--DBDFH, 1.04*BDB);
makeChange(BBD--CBDF--HB--DBDFH, BCG--CCAG--GH--DCGAE, 0.59*(BDB+BBD));
makeChange(BAC--CACE--GB--DACEG, BBD--CBDF--HB--DBDFH, 1.0*BBD);
setViewAbsolute(45, -35.2, 0);
figureLine();
SunCube();
makeMove(0.7*Z, -45, 1.5);
label("$U^{-0.5}$", 1.7*Z);
figureNext();
SunCube();
makeMove(0.7*X, 180, 1.5);
label("$R^2$", 1.7*Z);
figureNext();
SunCube();
makeMove(0.7*Z, 45, 1.5);
label("$U^{0.5}$", 1.7*Z);
figureNext();
SunCube();
makeMove(0.7*X, -180, 1.5);
label("$R^{-2}$", 1.7*Z);
figureEnd();
