include "algorithm.asyhdr";
include "../data/SunMinx.dat";

setView(-31.8, 0, 90);

figureBegin();
SunMinx();
triple center = findCenter(AG--AS--AD--AT--AH);
triple up = findCenter(AG--AO--AB--AP--AH);
triple left = findCenter(AI--AO--AG--AS--AJ);
triple right = findCenter(AK--AP--AH--AT--AL);
highline(AG--BGH--JG--BGS);
highline(AG--BGO--MG--BGS);
highline(AG--BGH--FG--BGO);
highline(AT--BTD--JT--BTH);
highline(AT--BTH--NT--BTL);
highline(AT--BTD--GT--BTL);
highline(BPH--BHP--FPHO);
highline(BPH--BHP--NHPL);
highline(BSJ--BJS--MJSO);
highline(BJS--BSJ--HJSC);
makeChange(AG--BGH--JG--BGS, AT--BTD--JT--BTH, 1.1*center+0.1*up);
makeChange(AT--BTD--JT--BTH, AG--BGH--JG--BGS, 0.9*center+0.4*up);
makeChange(BPH--BHP--FPHO, BJS--BSJ--HJSC, 1.4*center+0.1*(up+left));
makeChange(BSJ--BJS--MJSO, BPH--BHP--NHPL, 1.4*center+0.3*(up+left));
figureLine();
SunMinx();
makeMove(0.94*left, -36, 0.65);
label("$L^{-0.5}$", 1.4*up);
figureNext();
SunMinx();
makeMove(0.94*right, -36, 0.65);
label("$R^{-0.5}$", 1.4*up);
figureNext();
SunMinx();
makeMove(0.94*center, 144, 0.65);
label("$C^2$", 1.4*up);
figureLine();
SunMinx();
makeMove(0.94*right, 36, 0.65);
label("$R^{0.5}$", 1.4*up);
figureNext();
SunMinx();
makeMove(0.94*center, 72, 0.65);
label("$C$", 1.4*up);
figureNext();
SunMinx();
makeMove(0.94*left, 36, 0.65);
label("$L^{0.5}$", 1.4*up);
figureNext();
SunMinx();
makeMove(0.94*center, 144, 0.65);
label("$C^2$", 1.4*up);
figureEnd();
