include "algorithm.asyhdr";
include "../data/Tuttminx.dat";

figureBegin();
Tuttminx();
highline(BGB--BB2G--EGBD--CGBD);
highline(BGD--BD2G--EGDB--CGBD);
highline(BHD--BD2H--EHDB--CHBD);
highline(BGB--BB2G--EGBI--CGBI);
highline(BGD--BD2G--EGDJ--CGDJ);
highline(BHD--BD2H--EHDL--CHDL);
highline(BGB--CGBD--DGB--CGBI);
highline(BGD--CGBD--DGD--CGDJ);
highline(BHD--CHBD--DHD--CHDL);
makeChange(BGD--CGBD--DGD--CGDJ, BGB--CGBD--DGB--CGBI, 0.4*AG+0.55*CGBD);
makeChange(BGB--CGBD--DGB--CGBI, BHD--CHBD--DHD--CHDL, 1.3*BBD);
makeChange(BHD--CHBD--DHD--CHDL, BGD--CGBD--DGD--CGDJ, 1.3*BDB);
figureLine();
Tuttminx();
makeMove(0.315*(AB+AD+AG), -120, 0.5);
label("$C^{-1}$", 1.05*AG);
figureNext();
Tuttminx();
makeMove(0.315*(AB+AD+AH), 120, 0.5);
label("$D$", 1.05*AG);
figureNext();
Tuttminx();
makeMove(0.315*(AB+AD+AG), 120, 0.5);
label("$C$", 1.05*AG);
figureNext();
Tuttminx();
makeMove(0.77*AG, 72, 0.45);
label("$U$", 1.05*AG);
figureLine();
Tuttminx();
makeMove(0.315*(AB+AD+AG), -120, 0.5);
label("$C^{-1}$", 1.05*AG);
figureNext();
Tuttminx();
makeMove(0.315*(AB+AD+AH), -120, 0.5);
label("$D^{-1}$", 1.05*AG);
figureNext();
Tuttminx();
makeMove(0.315*(AB+AD+AG), 120, 0.5);
label("$C$", 1.05*AG);
figureNext();
Tuttminx();
makeMove(0.77*AG, -72, 0.45);
label("$U^{-1}$", 1.05*AG);
figureEnd();
