include "rubiks.asyhdr";

setView(45, -30, 0);

triple AA = (X+Y+Z)/2;
triple AB = (X+Y-Z)/2;
triple AC = (X-Y+Z)/2;
triple AD = (X-Y-Z)/2;
triple AE = (-X+Y+Z)/2;
triple AF = (-X+Y-Z)/2;
triple AG = (-X-Y+Z)/2;
triple AH = (-X-Y-Z)/2;

triple BA = X;
triple BB = Y;
triple BC = Z;
triple BD = -X;
triple BE = -Y;
triple BF = -Z;

triple CA = (X+Y)/2;
triple CB = (X-Y)/2;
triple CC = (-X+Y)/2;
triple CD = (-X-Y)/2;
triple CE = (X+Z)/2;
triple CF = (X-Z)/2;
triple CG = (-X+Z)/2;
triple CH = (-X-Z)/2;
triple CI = (Y+Z)/2;
triple CJ = (Y-Z)/2;
triple CK = (-Y+Z)/2;
triple CL = (-Y-Z)/2;

polygon(AA--CA--CE, Pink);
polygon(AA--CA--CI, Pink);
polygon(AA--CE--CI, Pink);
polygon(AB--CA--CF, Pink);
polygon(AB--CA--CJ, Pink);
polygon(AB--CF--CJ, Pink);
polygon(AC--CB--CE, Pink);
polygon(AC--CB--CK, Pink);
polygon(AC--CE--CK, Pink);
polygon(AD--CB--CF, Pink);
polygon(AD--CB--CL, Pink);
polygon(AD--CF--CL, Pink);
polygon(AE--CC--CG, Pink);
polygon(AE--CC--CI, Pink);
polygon(AE--CG--CI, Pink);
polygon(AF--CC--CH, Pink);
polygon(AF--CC--CJ, Pink);
polygon(AF--CH--CJ, Pink);
polygon(AG--CD--CG, Pink);
polygon(AG--CD--CK, Pink);
polygon(AG--CG--CK, Pink);
polygon(AH--CD--CH, Pink);
polygon(AH--CD--CL, Pink);
polygon(AH--CH--CL, Pink);

polygon(BA--CA--CE, LightBlue);
polygon(BA--CA--CF, LightBlue);
polygon(BA--CB--CE, LightBlue);
polygon(BA--CB--CF, LightBlue);
polygon(BB--CA--CI, LightBlue);
polygon(BB--CA--CJ, LightBlue);
polygon(BB--CC--CI, LightBlue);
polygon(BB--CC--CJ, LightBlue);
polygon(BC--CE--CI, LightBlue);
polygon(BC--CE--CK, LightBlue);
polygon(BC--CG--CI, LightBlue);
polygon(BC--CG--CK, LightBlue);
polygon(BD--CC--CG, LightBlue);
polygon(BD--CC--CH, LightBlue);
polygon(BD--CD--CG, LightBlue);
polygon(BD--CD--CH, LightBlue);
polygon(BE--CB--CK, LightBlue);
polygon(BE--CB--CL, LightBlue);
polygon(BE--CD--CK, LightBlue);
polygon(BE--CD--CL, LightBlue);
polygon(BF--CF--CJ, LightBlue);
polygon(BF--CF--CL, LightBlue);
polygon(BF--CH--CJ, LightBlue);
polygon(BF--CH--CL, LightBlue);
