include "rubiks.asyhdr";

setView(0, 18, 0);

real r = (sqrt(5)-1)/2;
real t = 1-r;

triple AA = X+r*Y;
triple AB = X-r*Y;
triple AC = -X+r*Y;
triple AD = -X-r*Y;
triple AE = Y+r*Z;
triple AF = Y-r*Z;
triple AG = -Y+r*Z;
triple AH = -Y-r*Z;
triple AI = Z+r*X;
triple AJ = Z-r*X;
triple AK = -Z+r*X;
triple AL = -Z-r*X;

triple BA = t*X+Y;
triple BB = -t*X+Y;
triple BC = t*X-Y;
triple BD = -t*X-Y;
triple BE = t*Y+Z;
triple BF = -t*Y+Z;
triple BG = t*Y-Z;
triple BH = -t*Y-Z;
triple BI = t*Z+X;
triple BJ = -t*Z+X;
triple BK = t*Z-X;
triple BL = -t*Z-X;
triple BM = r*(X+Y+Z);
triple BN = r*(X+Y-Z);
triple BO = r*(X-Y+Z);
triple BP = r*(X-Y-Z);
triple BQ = r*(-X+Y+Z);
triple BR = r*(-X+Y-Z);
triple BS = r*(-X-Y+Z);
triple BT = r*(-X-Y-Z);

triple CA = (AA+AB)/2;
triple CB = (AC+AD)/2;
triple CC = (AE+AF)/2;
triple CD = (AG+AH)/2;
triple CE = (AI+AJ)/2;
triple CF = (AK+AL)/2;
triple CG = (AA+AE)/2;
triple CH = (AA+AF)/2;
triple CI = (AA+AI)/2;
triple CJ = (AA+AK)/2;
triple CK = (AB+AG)/2;
triple CL = (AB+AH)/2;
triple CM = (AB+AI)/2;
triple CN = (AB+AK)/2;
triple CO = (AC+AE)/2;
triple CP = (AC+AF)/2;
triple CQ = (AC+AJ)/2;
triple CR = (AC+AL)/2;
triple CS = (AD+AG)/2;
triple CT = (AD+AH)/2;
triple CU = (AD+AJ)/2;
triple CV = (AD+AL)/2;
triple CW = (AE+AI)/2;
triple CX = (AE+AJ)/2;
triple CY = (AF+AK)/2;
triple CZ = (AF+AL)/2;
triple CAA = (AG+AI)/2;
triple CAB = (AG+AJ)/2;
triple CAC = (AH+AK)/2;
triple CAD = (AH+AL)/2;

polygon(AA--CA--CI, LightBlue);
polygon(AA--CI--CG, LightBlue);
polygon(AA--CG--CH, LightBlue);
polygon(AA--CH--CJ, LightBlue);
polygon(AA--CJ--CA, LightBlue);
polygon(AB--CA--CM, LightBlue);
polygon(AB--CM--CK, LightBlue);
polygon(AB--CK--CL, LightBlue);
polygon(AB--CL--CN, LightBlue);
polygon(AB--CN--CA, LightBlue);
polygon(AC--CB--CQ, LightBlue);
polygon(AC--CQ--CO, LightBlue);
polygon(AC--CO--CP, LightBlue);
polygon(AC--CP--CR, LightBlue);
polygon(AC--CR--CB, LightBlue);
polygon(AD--CB--CU, LightBlue);
polygon(AD--CU--CS, LightBlue);
polygon(AD--CS--CT, LightBlue);
polygon(AD--CT--CV, LightBlue);
polygon(AD--CV--CB, LightBlue);
polygon(AE--CC--CG, LightBlue);
polygon(AE--CG--CW, LightBlue);
polygon(AE--CW--CX, LightBlue);
polygon(AE--CX--CO, LightBlue);
polygon(AE--CO--CC, LightBlue);
polygon(AF--CC--CH, LightBlue);
polygon(AF--CH--CY, LightBlue);
polygon(AF--CY--CZ, LightBlue);
polygon(AF--CZ--CP, LightBlue);
polygon(AF--CP--CC, LightBlue);
polygon(AG--CD--CK, LightBlue);
polygon(AG--CK--CAA, LightBlue);
polygon(AG--CAA--CAB, LightBlue);
polygon(AG--CAB--CS, LightBlue);
polygon(AG--CS--CD, LightBlue);
polygon(AH--CD--CL, LightBlue);
polygon(AH--CL--CAC, LightBlue);
polygon(AH--CAC--CAD, LightBlue);
polygon(AH--CAD--CT, LightBlue);
polygon(AH--CT--CD, LightBlue);
polygon(AI--CE--CW, LightBlue);
polygon(AI--CW--CI, LightBlue);
polygon(AI--CI--CM, LightBlue);
polygon(AI--CM--CAA, LightBlue);
polygon(AI--CAA--CE, LightBlue);
polygon(AJ--CE--CX, LightBlue);
polygon(AJ--CX--CQ, LightBlue);
polygon(AJ--CQ--CU, LightBlue);
polygon(AJ--CU--CAB, LightBlue);
polygon(AJ--CAB--CE, LightBlue);
polygon(AK--CF--CY, LightBlue);
polygon(AK--CY--CJ, LightBlue);
polygon(AK--CJ--CN, LightBlue);
polygon(AK--CN--CAC, LightBlue);
polygon(AK--CAC--CF, LightBlue);
polygon(AL--CF--CZ, LightBlue);
polygon(AL--CZ--CR, LightBlue);
polygon(AL--CR--CV, LightBlue);
polygon(AL--CV--CAD, LightBlue);
polygon(AL--CAD--CF, LightBlue);

polygon(BA--CC--CG, Pink);
polygon(BA--CC--CH, Pink);
polygon(BA--CG--CH, Pink);
polygon(BB--CC--CO, Pink);
polygon(BB--CC--CP, Pink);
polygon(BB--CO--CP, Pink);
polygon(BC--CD--CK, Pink);
polygon(BC--CD--CL, Pink);
polygon(BC--CK--CL, Pink);
polygon(BD--CD--CS, Pink);
polygon(BD--CD--CT, Pink);
polygon(BD--CS--CT, Pink);
polygon(BE--CE--CW, Pink);
polygon(BE--CE--CX, Pink);
polygon(BE--CW--CX, Pink);
polygon(BF--CE--CAA, Pink);
polygon(BF--CE--CAB, Pink);
polygon(BF--CAA--CAB, Pink);
polygon(BG--CF--CY, Pink);
polygon(BG--CF--CZ, Pink);
polygon(BG--CY--CZ, Pink);
polygon(BH--CF--CAC, Pink);
polygon(BH--CF--CAD, Pink);
polygon(BH--CAC--CAD, Pink);
polygon(BI--CA--CI, Pink);
polygon(BI--CA--CM, Pink);
polygon(BI--CI--CM, Pink);
polygon(BJ--CA--CJ, Pink);
polygon(BJ--CA--CN, Pink);
polygon(BJ--CJ--CN, Pink);
polygon(BK--CB--CQ, Pink);
polygon(BK--CB--CU, Pink);
polygon(BK--CQ--CU, Pink);
polygon(BL--CB--CR, Pink);
polygon(BL--CB--CV, Pink);
polygon(BL--CR--CV, Pink);
polygon(BM--CI--CG, Pink);
polygon(BM--CI--CW, Pink);
polygon(BM--CG--CW, Pink);
polygon(BN--CH--CJ, Pink);
polygon(BN--CH--CY, Pink);
polygon(BN--CJ--CY, Pink);
polygon(BO--CK--CM, Pink);
polygon(BO--CK--CAA, Pink);
polygon(BO--CM--CAA, Pink);
polygon(BP--CL--CN, Pink);
polygon(BP--CL--CAC, Pink);
polygon(BP--CN--CAC, Pink);
polygon(BQ--CO--CQ, Pink);
polygon(BQ--CO--CX, Pink);
polygon(BQ--CQ--CX, Pink);
polygon(BR--CP--CR, Pink);
polygon(BR--CP--CZ, Pink);
polygon(BR--CR--CZ, Pink);
polygon(BS--CS--CU, Pink);
polygon(BS--CS--CAB, Pink);
polygon(BS--CU--CAB, Pink);
polygon(BT--CT--CV, Pink);
polygon(BT--CT--CAD, Pink);
polygon(BT--CV--CAD, Pink);

