//
include "sun.asyhdr";

setView(30, -30, 60);

real p = (sqrt(5) + 1) / 2;
real q = p - 1;
real r = 1 / sqrt(3);
real x = ((p + sqrt(p - 5 / 27)) / 2) ^ (1 / 3) + ((p - sqrt(p - 5 / 27)) / 2) ^ (1 / 3);
real y = x * sqrt(209 * ((104 * p - 7) * x ^ 2 + (52 + 153 * p) * x + (195 - p))) / sqrt(3 * (x * p + 1 + p + (1 / x))) / 209;

transform3 rxy = reflect(O, X, Y);
transform3 rxz = reflect(O, X, Z);
transform3 ryz = reflect(O, Y, Z);
transform3 s = rotate(120, X + Y + Z);

triple AA = q * X + Y;
triple AB = rxz * AA;
triple AC = ryz * AA;
triple AD = rxz * AC;
triple AE = s * AA;
triple AF = rxy * AE;
triple AG = rxz * AE;
triple AH = rxy * AG;
triple AI = s * AE;
triple AJ = ryz * AI;
triple AK = rxy * AI;
triple AL = ryz * AK;

triple BA = r * (p * X + q * Y);
triple BB = ryz * BA;
triple BC = rxz * BA;
triple BD = rxz * BB;
triple BE = s * BA;
triple BF = rxz * BE;
triple BG = rxy * BF;
triple BH = rxz * BG;
triple BI = s * BE;
triple BJ = rxy * BI;
triple BK = ryz * BI;
triple BL = rxy * BK;
triple BM = r * (X + Y + Z);
triple BN = rxy * BM;
triple BO = rxz * BM;
triple BP = rxy * BO;
triple BQ = ryz * BM;
triple BR = rxy * BQ;
triple BS = rxz * BQ;
triple BT = rxy * BS;

transform3 saa = rotate(72, AA);
transform3 sab = rotate(72, AB);
transform3 sac = rotate(72, AC);
transform3 sad = rotate(72, AD);
transform3 sae = rotate(72, AE);
transform3 saf = rotate(72, AF);
transform3 sag = rotate(72, AG);
transform3 sah = rotate(72, AH);
transform3 sai = rotate(72, AI);
transform3 saj = rotate(72, AJ);
transform3 sak = rotate(72, AK);
transform3 sal = rotate(72, AL);
transform3 sbd = rotate(120, BD);
transform3 sbe = rotate(120, BE);
transform3 sbi = rotate(120, BI);
transform3 sbk = rotate(120, BK);
transform3 sbl = rotate(120, BL);
transform3 sbm = rotate(120, BM);
transform3 sbn = rotate(120, BN);
transform3 sbo = rotate(120, BO);
transform3 sbq = rotate(120, BQ);
transform3 sbr = rotate(120, BR);
transform3 sbs = rotate(120, BS);

triple CA = y * unit(p * sqrt(x + 1 - p) * X + (x ^ 2) * p * sqrt((x - 1 - (1 / x)) * p) * Y + sqrt((x ^ 2) * (1 + 2 * p) - p) * Z);
triple CB = sae * CA;
triple CC = sae * CB;
triple CD = sae * CC;
triple CE = sae * CD;
triple CF = sbm * CA;
triple CG = sai * CF;
triple CH = sai * CG;
triple CI = sai * CH;
triple CJ = sai * CI;
triple CK = sbe * CA;
triple CL = saa * CK;
triple CM = saa * CL;
triple CN = saa * CM;
triple CO = saa * CN;
triple CP = sbq * CA;
triple CQ = sac * CP;
triple CR = sac * CQ;
triple CS = sac * CR;
triple CT = sac * CS;
triple DA = sbk * CA;
triple DB = saj * DA;
triple DC = saj * DB;
triple DD = saj * DC;
triple DE = saj * DD;
triple DF = sbi * CA;
triple DG = sag * DF;
triple DH = sag * DG;
triple DI = sag * DH;
triple DJ = sag * DI;
triple DK = sbo * DF;
triple DL = sab * DK;
triple DM = sab * DL;
triple DN = sab * DM;
triple DO = sab * DN;
triple DP = sbn * CK;
triple DQ = sak * DP;
triple DR = sak * DQ;
triple DS = sak * DR;
triple DT = sak * DS;
triple EA = sbr * CP;
triple EB = saf * EA;
triple EC = saf * EB;
triple ED = saf * EC;
triple EE = saf * ED;
triple EF = sbd * DA;
triple EG = sal * EF;
triple EH = sal * EG;
triple EI = sal * EH;
triple EJ = sal * EI;
triple EK = sbl * EA;
triple EL = sah * EK;
triple EM = sah * EL;
triple EN = sah * EM;
triple EO = sah * EN;
triple EP = sbs * DA;
triple EQ = sad * EP;
triple ER = sad * EQ;
triple ES = sad * ER;
triple ET = sad * ES;

transform3 t = rotate(-20, DN);

bool[] conf = new bool[] {true, false, true, false, true, true, true, false, true, false, true, false};

face fca = constructFace(CA, BM, conf);
face fcb = constructFace(CB, BE, conf);
face fcc = constructFace(CC, BQ, conf);
face fcd = constructFace(CD, BK, conf);
face fce = constructFace(CE, BI, conf);
face fcf = constructFace(CF, BM, conf);
face fcg = constructFace(CG, BI, conf);
face fch = constructFace(CH, BO, conf);
face fci = constructFace(CI, BC, conf);
face fcj = constructFace(CJ, BA, conf);
face fck = constructFace(CK, BH, conf);
face fcl = constructFace(CL, BE, conf);
face fcm = constructFace(CM, BM, conf);
face fcn = constructFace(CN, BA, conf);
face fco = constructFace(CO, BN, conf);
face fcp = constructFace(CP, BR, conf);
face fcq = constructFace(CQ, BB, conf);
face fcr = constructFace(CR, BQ, conf);
face fcs = constructFace(CS, BE, conf);
face fct = constructFace(CT, BH, conf);
face fda = constructFace(DA, BB, conf);
face fdb = constructFace(DB, BD, conf);
face fdc = constructFace(DC, BS, conf);
face fdd = constructFace(DD, BK, conf);
face fde = constructFace(DE, BQ, conf);
face fdf = constructFace(DF, BK, conf);
face fdg = constructFace(DG, BS, conf);
face fdh = constructFace(DH, BF, conf);
face fdi = constructFace(DI, BO, conf);
face fdj = constructFace(DJ, BI, conf);
face fdk = constructFace(DK, BG, conf);
face fdl = constructFace(DL, BP, conf);
face fdm = constructFace(DM, BC, conf);
face fdn = constructFace(DN, BO, conf);
face fdo = constructFace(DO, BF, conf);
face fdp = constructFace(DP, BA, conf);
face fdq = constructFace(DQ, BC, conf);
face fdr = constructFace(DR, BP, conf);
face fds = constructFace(DS, BJ, conf);
face fdt = constructFace(DT, BN, conf);
face fea = constructFace(EA, BR, conf);
face feb = constructFace(EB, BH, conf);
face fec = constructFace(EC, BN, conf);
face fed = constructFace(ED, BJ, conf);
face fee = constructFace(EE, BL, conf);
face fef = constructFace(EF, BT, conf);
face feg = constructFace(EG, BD, conf);
face feh = constructFace(EH, BB, conf);
face fei = constructFace(EI, BR, conf);
face fej = constructFace(EJ, BL, conf);
face fek = constructFace(EK, BJ, conf);
face fel = constructFace(EL, BP, conf);
face fem = constructFace(EM, BG, conf);
face fen = constructFace(EN, BT, conf);
face feo = constructFace(EO, BL, conf);
face fep = constructFace(EP, BG, conf);
face feq = constructFace(EQ, BF, conf);
face fer = constructFace(ER, BS, conf);
face fes = constructFace(ES, BD, conf);
face fet = constructFace(ET, BT, conf);

real d = length(fca.P[0]-fca.R[0]) / 2;
glueFaces(fca, fcb, fcm, d);
glueFaces(fcb, fcc, fcs, d);
glueFaces(fcc, fcd, fde, d);
glueFaces(fcd, fce, fdf, d);
glueFaces(fce, fca, fcg, d);
glueFaces(fcf, fcg, fca, d);
glueFaces(fcg, fch, fdj, d);
glueFaces(fch, fci, fdn, d);
glueFaces(fci, fcj, fdq, d);
glueFaces(fcj, fcf, fcn, d);
glueFaces(fck, fcl, fct, d);
glueFaces(fcl, fcm, fcb, d);
glueFaces(fcm, fcn, fcf, d);
glueFaces(fcn, fco, fdp, d);
glueFaces(fco, fck, fec, d);
glueFaces(fcp, fcq, fei, d);
glueFaces(fcq, fcr, fda, d);
glueFaces(fcr, fcs, fcc, d);
glueFaces(fcs, fct, fcl, d);
glueFaces(fct, fcp, feb, d);
glueFaces(fda, fdb, feh, d);
glueFaces(fdb, fdc, fes, d);
glueFaces(fdc, fdd, fdg, d);
glueFaces(fdd, fde, fcd, d);
glueFaces(fde, fda, fcr, d);
glueFaces(fdf, fdg, fdd, d);
glueFaces(fdg, fdh, fer, d);
glueFaces(fdh, fdi, fdo, d);
glueFaces(fdi, fdj, fch, d);
glueFaces(fdj, fdf, fce, d);
glueFaces(fdk, fdl, fem, d);
glueFaces(fdl, fdm, fdr, d);
glueFaces(fdm, fdn, fci, d);
glueFaces(fdn, fdo, fdi, d);
glueFaces(fdo, fdk, feq, d);
glueFaces(fdp, fdq, fcj, d);
glueFaces(fdq, fdr, fdm, d);
glueFaces(fdr, fds, fel, d);
glueFaces(fds, fdt, fed, d);
glueFaces(fdt, fdp, fco, d);
glueFaces(fea, feb, fcp, d);
glueFaces(feb, fec, fck, d);
glueFaces(fec, fed, fdt, d);
glueFaces(fed, fee, fek, d);
glueFaces(fee, fea, fej, d);
glueFaces(fef, feg, fet, d);
glueFaces(feg, feh, fdb, d);
glueFaces(feh, fei, fcq, d);
glueFaces(fei, fej, fea, d);
glueFaces(fej, fef, feo, d);
glueFaces(fek, fel, fds, d);
glueFaces(fel, fem, fdl, d);
glueFaces(fem, fen, fep, d);
glueFaces(fen, feo, fef, d);
glueFaces(feo, fek, fee, d);
glueFaces(fep, feq, fdk, d);
glueFaces(feq, fer, fdh, d);
glueFaces(fer, fes, fdc, d);
glueFaces(fes, fet, feg, d);
glueFaces(fet, fep, fen, d);

vertex5 va = constructVertex5(fck, fcl, fcm, fcn, fco);
vertex5 vb = constructVertex5(fdk, fdl, fdm, fdn, fdo);
vertex5 vc = constructVertex5(fcp, fcq, fcr, fcs, fct);
vertex5 vd = constructVertex5(fep, feq, fer, fes, fet);
vertex5 ve = constructVertex5(fca, fcb, fcc, fcd, fce);
vertex5 vf = constructVertex5(fea, feb, fec, fed, fee);
vertex5 vg = constructVertex5(fdf, fdg, fdh, fdi, fdj);
vertex5 vh = constructVertex5(fek, fel, fem, fen, feo);
vertex5 vi = constructVertex5(fcf, fcg, fch, fci, fcj);
vertex5 vj = constructVertex5(fda, fdb, fdc, fdd, fde);
vertex5 vk = constructVertex5(fdp, fdq, fdr, fds, fdt);
vertex5 vl = constructVertex5(fef, feg, feh, fei, fej);

drawFace(fca, White + Platina);
drawFace(fcb, White + Lilac);
drawFace(fcc, White + Brown);
drawFace(fcd, White + Ametist);
drawFace(fce, White + Garnet);
drawFace(fcf, Red + Platina);
drawFace(fcg, Red + Lilac);
drawFace(fch, Red + Brown, t, 1);
drawFace(fci, Red + Ametist, t, 9);
drawFace(fcj, Red + Garnet);
drawFace(fck, Blue + Platina);
drawFace(fcl, Blue + Lilac);
drawFace(fcm, Blue + Brown);
drawFace(fcn, Blue + Ametist);
drawFace(fco, Blue + Garnet);
drawFace(fcp, Yellow + Platina);
drawFace(fcq, Yellow + Lilac);
drawFace(fcr, Yellow + Brown);
drawFace(fcs, Yellow + Ametist);
drawFace(fct, Yellow + Garnet);
drawFace(fda, Violet + Platina);
drawFace(fdb, Violet + Lilac);
drawFace(fdc, Violet + Brown);
drawFace(fdd, Violet + Ametist);
drawFace(fde, Violet + Garnet);
drawFace(fdf, Green + Platina);
drawFace(fdg, Green + Lilac);
drawFace(fdh, Green + Brown);
drawFace(fdi, Green + Ametist, t, 11);
drawFace(fdj, Green + Garnet);
drawFace(fdk, Lime + Platina);
drawFace(fdl, Lime + Lilac);
drawFace(fdm, Lime + Brown, t, 3);
drawFace(fdn, Lime + Ametist, t);
drawFace(fdo, Lime + Garnet, t, 7);
drawFace(fdp, Pink + Platina);
drawFace(fdq, Pink + Lilac);
drawFace(fdr, Pink + Brown);
drawFace(fds, Pink + Ametist);
drawFace(fdt, Pink + Garnet);
drawFace(fea, LightGreen + Platina);
drawFace(feb, LightGreen + Lilac);
drawFace(fec, LightGreen + Brown);
drawFace(fed, LightGreen + Ametist);
drawFace(fee, LightGreen + Garnet);
drawFace(fef, Orange + Platina);
drawFace(feg, Orange + Lilac);
drawFace(feh, Orange + Brown);
drawFace(fei, Orange + Ametist);
drawFace(fej, Orange + Garnet);
drawFace(fek, LightBlue + Platina);
drawFace(fel, LightBlue + Lilac);
drawFace(fem, LightBlue + Brown);
drawFace(fen, LightBlue + Ametist);
drawFace(feo, LightBlue + Garnet);
drawFace(fep, Grey + Platina);
drawFace(feq, Grey + Lilac);
drawFace(fer, Grey + Brown);
drawFace(fes, Grey + Ametist);
drawFace(fet, Grey + Garnet);

drawVertex5(va, Tan);
drawVertex5(vb, Tan, t, 3);
drawVertex5(vc, Tan);
drawVertex5(vd, Tan);
drawVertex5(ve, Tan);
drawVertex5(vf, Tan);
drawVertex5(vg, Tan);
drawVertex5(vh, Tan);
drawVertex5(vi, Tan);
drawVertex5(vj, Tan);
drawVertex5(vk, Tan);
drawVertex5(vl, Tan);

